import AppKit

// Usage:
//   S005 images <scratch>                          write plain-colour TIFFs of about 1, 10 and 50 MB
//   S005 watch [--level count|types|data] [--interval 1.0] [--seconds 300]
//                                                  poll the general pasteboard; the item present at start is not read
//   S005 write-marker | write-plain                put a self-made dummy item (with or without marker types) on the pasteboard
// <scratch> must be a direct child of $TMPDIR whose name starts with "s005-".
// watch quits by itself after --seconds (default 300). Ctrl+C also stops it.

setvbuf(stdout, nil, _IOLBF, 0)
let arguments = Array(CommandLine.arguments.dropFirst())

func value(_ flag: String) -> String? {
    guard let i = arguments.firstIndex(of: flag), i + 1 < arguments.count else { return nil }
    return arguments[i + 1]
}

func resolve(_ path: String) -> String? {
    guard let raw = realpath(path, nil) else { return nil }
    defer { free(raw) }
    return String(cString: raw)
}

switch arguments.first {
case "images":
    guard arguments.count == 2, let scratch = resolve(arguments[1]), let tmp = resolve(NSTemporaryDirectory()),
          URL(fileURLWithPath: scratch).lastPathComponent.hasPrefix("s005-"),
          URL(fileURLWithPath: scratch).deletingLastPathComponent().path == tmp else {
        print("refused: scratch folder must be a direct child of $TMPDIR named s005-*")
        exit(2)
    }
    exit(Images.write(into: scratch) ? 0 : 1)

case "write-marker", "write-plain":
    // Self-made test items, not a real password manager: dummy text, plus marker types for write-marker.
    MainActor.assumeIsolated {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString("s005-dummy", forType: .string)
        if arguments.first == "write-marker" {
            for marker in Watch.markerTypes.dropLast() { // ConcealedType, TransientType, AutoGeneratedType
                item.setData(Data(), forType: NSPasteboard.PasteboardType(marker))
            }
        }
        let ok = pasteboard.writeObjects([item])
        print("\(arguments.first ?? ""): \(ok ? "written" : "failed"), changeCount \(pasteboard.changeCount)")
    }

case "watch":
    let level = value("--level").flatMap(Level.init(rawValue:)) ?? .count
    let interval = value("--interval").flatMap(Double.init) ?? 1.0
    let seconds = value("--seconds").flatMap(Int.init) ?? 300
    guard interval >= 0.1 else { print("refused: interval below 0.1 s"); exit(2) }
    print("pid \(ProcessInfo.processInfo.processIdentifier), stops after \(seconds) s or Ctrl+C")
    signal(SIGINT, SIG_IGN)
    let sigint = DispatchSource.makeSignalSource(signal: SIGINT, queue: .main)
    MainActor.assumeIsolated {
        let app = NSApplication.shared
        app.setActivationPolicy(.accessory)
        let watch = Watch(level: level, interval: interval)
        watch.start()
        sigint.setEventHandler { MainActor.assumeIsolated { watch.stop(); exit(0) } }
        sigint.resume()
        DispatchQueue.main.asyncAfter(deadline: .now() + .seconds(seconds)) {
            MainActor.assumeIsolated { watch.stop(); exit(0) }
        }
        app.run()
    }

default:
    print("usage: S005 images <scratch> | S005 watch [--level count|types|data] [--interval s] [--seconds n]")
    exit(2)
}
