import AppKit

/// How far the watcher goes when the change count moves.
enum Level: String {
    case count  // (a) change count only
    case types  // (b) type identifiers only
    case data   // (c) read the data of every type; print sizes and timings only
}

/// Polls NSPasteboard.general.changeCount. The item already on the pasteboard at start is never read.
@MainActor
final class Watch {
    static let markerTypes = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
                              "org.nspasteboard.AutoGeneratedType", "org.nspasteboard.source"]
    private let pasteboard = NSPasteboard.general
    private let level: Level
    private let interval: Double
    private var lastCount: Int
    private var timer: Timer?
    private(set) var changes = 0

    init(level: Level, interval: Double) {
        self.level = level
        self.interval = interval
        lastCount = pasteboard.changeCount
        Log.line("start: level \(level.rawValue), interval \(interval) s, changeCount \(lastCount), "
                 + "accessBehavior \(accessBehavior()); current item not read")
    }

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: interval, repeats: true) { _ in
            MainActor.assumeIsolated { self.poll() }
        }
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        Log.line("stop: \(changes) changes seen")
    }

    private func poll() {
        let count = pasteboard.changeCount
        guard count != lastCount else { return }
        lastCount = count
        changes += 1
        Log.line("change #\(changes): changeCount \(count), accessBehavior before \(accessBehavior())")
        switch level {
        case .count: break
        case .types: readTypeList()
        case .data: readTypes(); readData()
        }
        Log.line("change #\(changes): accessBehavior after \(accessBehavior())")
    }

    /// Level (b): NSPasteboard.types only, no item objects and no data.
    private func readTypeList() {
        let t0 = DispatchTime.now().uptimeNanoseconds
        let types = pasteboard.types?.map(\.rawValue)
        let elapsed = Log.ms(since: t0)
        guard let types else { Log.line("  types: nil (read failed or denied), \(elapsed)"); return }
        let markers = Self.markerTypes.filter(types.contains)
        Log.line("  types (\(types.count)), read in \(elapsed): \(types.joined(separator: ", "))")
        Log.line("  marker types: \(markers.isEmpty ? "none" : markers.joined(separator: ", "))")
    }

    /// Level (c), first step: the item list and each item's types.
    private func readTypes() {
        let t0 = DispatchTime.now().uptimeNanoseconds
        let items = pasteboard.pasteboardItems
        let elapsed = Log.ms(since: t0)
        guard let items else { Log.line("  pasteboardItems: nil (read failed or denied), \(elapsed)"); return }
        Log.line("  items: \(items.count), read in \(elapsed)")
        for (i, item) in items.enumerated() {
            let types = item.types.map(\.rawValue)
            let markers = Self.markerTypes.filter(types.contains)
            Log.line("  item \(i) types (\(types.count)): \(types.joined(separator: ", "))")
            Log.line("  item \(i) marker types: \(markers.isEmpty ? "none" : markers.joined(separator: ", "))")
        }
    }

    /// Reads every type of every item. Prints byte counts and timings, never the bytes.
    private func readData() {
        guard let items = pasteboard.pasteboardItems else { Log.line("  data: no items (read failed or denied)"); return }
        var total = 0
        let tAll = DispatchTime.now().uptimeNanoseconds
        for (i, item) in items.enumerated() {
            for type in item.types {
                let t0 = DispatchTime.now().uptimeNanoseconds
                let size = item.data(forType: type)?.count
                total += size ?? 0
                Log.line("  item \(i) \(type.rawValue): \(size.map { "\($0) bytes" } ?? "nil (read failed or denied)"), \(Log.ms(since: t0))")
            }
        }
        Log.line("  data total \(total) bytes, all reads \(Log.ms(since: tAll))")
    }

    /// NSPasteboard.accessBehavior exists from macOS 15.4 (SDK header).
    private func accessBehavior() -> String {
        guard #available(macOS 15.4, *) else { return "n/a before 15.4" }
        return Self.describe(pasteboard.accessBehavior)
    }

    @available(macOS 15.4, *)
    static func describe(_ behavior: NSPasteboard.AccessBehavior) -> String {
        switch behavior {
        case .default: "default"
        case .ask: "ask"
        case .alwaysAllow: "alwaysAllow"
        case .alwaysDeny: "alwaysDeny"
        @unknown default: "unknown(\(behavior.rawValue))"
        }
    }
}
